source 'https://github.com/CocoaPods/Specs.git'
target 'Detourist' do
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Auth'
  
  pod 'FirebaseUI/Google'
end
